### ISSUE TITLE
关于引用Unexpected token import

### ISSUE THREAD

**Issue by yiuyiu** [LS1231/vue-preview#1]
请教下那啥我用的 vue-cli 引用其他的模块用的import 都没问题，import vue-preview 就会显示 unexpected token import

**Comment by LS1231** [comment]
如果你的vue版本为1.*的话，就会有这个问题。这个插件目前仅支持vue2.0以上版本。

**Comment by Cydmi** [comment]
> {
    test: /vue-preview.src.*?js$/,
    loader: 'babel'
}
`webpack.config.js` 加这个就不会了出错了。vue2.0` @ yiuyiu
