### ISSUE TITLE
版本1.0.5，：src必须是“src”，否则点看图片出不来，缩略图能出来

### ISSUE THREAD

**Issue by lwdmengda** [LS1231/vue-preview#10]
template那里，只能这样：
<img class="preview-img" v-for="(item, index) in list" :src="item.src" height="100" @click="$preview.open(index, list)">
不能这样：
<img class="preview-img" v-for="(item, index) in list" :src="item.picSrc" height="100" @click="$preview.open(index, list)">

数据定义：
        list: [{
          src: 'https://placekitten.com/600/400',  //不能是picSrc
          w: 600,
          h: 400
        }, {
          src: 'https://placekitten.com/1200/900',
          w: 1200,
          h: 900
        }]

**Comment by WLyKan** [comment]
这个是photoswiper本身的属性，像`w`,`h`一样必须一致的
