### ISSUE TITLE
$preview.open报错

### ISSUE THREAD

**Issue by evan2579429110** [LS1231/vue-preview#11]
请问部署好之后发现报这个错误
Vue warn]: Property or method "$preview" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
还有这个错误
index.js:50301 Uncaught TypeError: Cannot read property 'open' of undefined

然后原代码使用是
vue:
    import VuePreview from 'vue-preview';
components: {
            VuePreview
        }

template:

<template>
    <img class="preview-img"  v-for="(evidence,index) in questionnaire.evidences" :src="evidence.src" height="100" @click="$preview.open(index, questionnaire.evidences)">
</template>

数据格式也当正常，就是还多一个字段 type:img,

感觉是不支持$preview.open()这种写法，请问是什么原因

**Comment by LS1231** [comment]
请检查插件的使用姿势是否正确。
import VuePreview from 'vue-preview'
Vue.use(VuePreview)

**Comment by SidFeng** [comment]
现在不支持$preview.open()这种写法了吗？
