### ISSUE TITLE
webpack打包出现出错

### ISSUE THREAD

**Issue by ProMonkey** [LS1231/vue-preview#18]
`Module not found: Error: Cannot resolve 'file' or 'directory' ./default-skin.png in /node_modules/vue-preview/src/plugins/preview`

**引入url-loader后也不行**

**Comment by LS1231** [comment]
安装的依赖包有问题。尝试删掉重新安装一遍。
npm i vue-preview -S --registry=https://registry.npm.taobao.org

**Comment by ProMonkey** [comment]
还是没用，你包里依赖了photoswipe，在default-skin目录下的default-skin.css引用目录下的图片有问题，没有被url-loader转换成base64，你有遇到过这个错误吗

**Comment by special-wen** [comment]
> 还是没用，你包里依赖了photoswipe，在default-skin目录下的default-skin.css引用目录下的图片有问题，没有被url-loader转换成base64，你有遇到过这个错误吗

哈喽  想问一下 你最后是怎么解决的呀
