### ISSUE TITLE
作者朋友您好，使用过程中遇到一个问题，有多组图片，点击下面的  都是从第一组出现放大效果，请问怎么解决？

### ISSUE THREAD

**Issue by suizhiwen** [LS1231/vue-preview#20]
![sdfasdf](https://user-images.githubusercontent.com/25659280/30101078-94489a76-931d-11e7-8944-7b9d9c1c61ff.png)

有多组图片，第一组正常，点第二组图片的时候，放大的效果是从第一组放大，缩小也是缩回第一组，请问这个问题怎么解决

**Comment by suizhiwen** [comment]
` <li class="friends-item" v-for="(friendsItem, itemIndex) in listData">
      <img class="previewer-demo-img photo-item"
           v-for="(item, i) in friendsItem.imgUrlList"
           :src="item.src"
           width="60"
           height="60"
           @click="show(i, itemIndex)">
      <div v-transfer-dom>
        <previewer :list="friendsItem.imgUrlList"
                   ref="previewer"
                   :options="options"></previewer>
      </div>
    </li>`

**Comment by suizhiwen** [comment]
` <li class="friends-item" v-for="(friendsItem, itemIndex) in listData">
      <img class="previewer-demo-img photo-item"
           v-for="(item, i) in friendsItem.imgUrlList"
           :src="item.src"
           width="60"
           height="60"
           @click="show(i, itemIndex)">
      <div v-transfer-dom>
        <previewer :list="friendsItem.imgUrlList"
                   ref="previewer"
                   :options="options"></previewer>
      </div>
    </li>`

**Comment by hukuiabc** [comment]
是么，我正要用呢

**Comment by xifat** [comment]
这个怎么调用呢？打包在webpack 里面的。

**Comment by Frank-MJ** [comment]
我也有这个需求，跟一楼的一样，有多组图片的时候，点击其中一张图片都是从这一组图片的第一张开始显示的，应该是点击当前图片显示的是当前的图片才对，请问作者怎么解决

**Comment by Frank-MJ** [comment]
@suizhiwen 这个问题你解决了嘛

**Comment by LS1231** [comment]
最新版已修复
