### ISSUE TITLE
将vue-preview 1.0.5加入项目后，npm run build打包报错。

### ISSUE THREAD

**Issue by cpfzone** [LS1231/vue-preview#21]
ERROR in static/js/vendor.debc40883c868827f080.js from UglifyJs
Unexpected token: name ($vm) [./~/_vue-preview@1.0.5@vue-preview/src/plugins/preview/index.js:2,0][static/js/vendor.debc40883c868827f080.js:35904,4]

  Build failed with errors.

**Comment by kamifun** [comment]
+1

**Comment by kamifun** [comment]
请问你的问题解决了吗

**Comment by kamifun** [comment]
看使用须知,在webpack配置文件加上babel-loader转换这个插件代码

**Comment by LS1231** [comment]
最新版已修复
