### ISSUE TITLE
引入报错，但是组件库里的确有这个组件

### ISSUE THREAD

**Issue by WRZack** [LS1231/vue-preview#27]
This dependency was not found:
* vue-preview in ./src/main.js
To install it,you can run:npm install --save vue-preview
已经执行了cnpm install --save vue-preview
组件库里已经有vue-preview的快捷方式到_vue-preview@1.0.5@vue-preview

**Comment by guanxy2017** [comment]
我也遇到了，请问你解决了吗？

**Comment by inspiredole** [comment]
`Failed to compile with 1 errors                                                                                                                                                                                         17:08:39
This dependency was not found:

* vue-preview in ./src/main.js

To install it, you can run: npm install --save vue-preview`

我也是

**Comment by klxin** [comment]
修改webpack.base.conf.js为 
{
    test: /vue-preview.src.*?js$/,
    loader: 'babel'
}

**Comment by WRZack** [comment]
klxin的方法可行

**Comment by WRZack** [comment]
klxin的方法可行
