### ISSUE TITLE
编译时es6不能转成es5，所以在部分低版本手机中无法正加载在页面

### ISSUE THREAD

**Issue by liusome** [LS1231/vue-preview#29]
![image](https://user-images.githubusercontent.com/13285305/35035723-3f504e26-fbad-11e7-99f6-758f15ea86e8.png)
请看下这个编译报错的问题吧。
let 没有被转成 var
![image](https://user-images.githubusercontent.com/13285305/35036010-f6d0cc4c-fbad-11e7-811a-b0afe860e8cd.png)

**Comment by LS1231** [comment]
已修复
