### ISSUE TITLE
可以正常使用，但是图标显示不出来

### ISSUE THREAD

**Issue by SidFeng** [LS1231/vue-preview#3]
![image](https://cloud.githubusercontent.com/assets/6702354/21480610/a810bc92-cb99-11e6-9e5d-406979070178.png)
貌似是背景图，svg加载不出来

**Comment by LS1231** [comment]
@SidFeng 请详细描述你遇到的问题

**Comment by SidFeng** [comment]
就是插件的下一页，上一页，放大等白色图标没了。default-skin.svg加载不出来

**Comment by LS1231** [comment]
你检查一下样式问题，其次是所有图标都是由一张精灵图提供的，可以检查一下那张图片是否加载成功，只能帮你到这里了。good luck

**Comment by fandudu** [comment]
我也遇到同样的问题，你们都有图标么？

**Comment by ClausClaus** [comment]
嗯！那个啥！图片的话如果你是使用webpack做的配置，那么你需要在webpack.config.js中加入对svg的解析。类似这样{
                test: /\.(png|jpg|gif|ttf|svg)$/,
                loader: 'url-loader?limit=4096'
            },
关键点在于后面的svg是我后来添加的

**Comment by xmgh5** [comment]
图片显示不出来，只有一片黑

**Comment by LS1231** [comment]
最新版已修复
