### ISSUE TITLE
引入这个文件 run build 报错，大佬怎么解决

### ISSUE THREAD

**Issue by picnic-yu** [LS1231/vue-preview#34]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ck-management-web@1.0.0 build: `webpack --progress --hide-modules --config build/webpack.prod.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ck-management-web@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-03-08T01_08_24_927Z-debug.log

**Comment by LS1231** [comment]
请下载最新版
npm i vue-preview -S
