### ISSUE TITLE
photoswipe无法安装

### ISSUE THREAD

**Issue by lilien1010** [LS1231/vue-preview#4]
➜  vue-preview git:(master) ✗ npm install photoswipe --save
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "install" "photoswipe" "--save"
npm ERR! node v7.3.0
npm ERR! npm  v4.0.5

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/Documents/vuex/vue-preview/npm-debug.log
➜  vue-preview git:(master) ✗ ll

**Comment by LS1231** [comment]
尝试切换npm镜像源来安装。
npm i vue-preview -S --registry=https://registry.npm.taobao.org
