### ISSUE TITLE
全局配置 w h

### ISSUE THREAD

**Issue by bulolo** [LS1231/vue-preview#6]
list: [{
          src: 'https://placekitten.com/600/400',
          w: 600,
          h: 400
        }, {
          src: 'https://placekitten.com/1200/900',
          w: 1200,
          h: 900
        }]

一般从网络获取图片数据源,不带 w h,删掉 w,h 又报错。是否能够全局配置？

**Comment by puregardenia** [comment]
```
var img =new Image()
img.src = url
```

通过 `img.naturalWidth` 和 `img.naturalHeight` 可以获取到原始图片大小，如果不需要考虑到浏览器兼容的话
