### ISSUE TITLE
怎么在插件里使用两张图片的地址

### ISSUE THREAD

**Issue by duanpf** [LS1231/vue-preview#7]
现在缩略图和弹出来的图都是同一个路径，怎么在插件里配置达到缩略图和弹出来的图分别引用不同大小的图片路径呢

**Comment by LS1231** [comment]
不带这个功能哈

**Comment by duanpf** [comment]
拓展这个功能复杂？ 如果缩略图和大图都用同一个缩略图的地址，因为被放大了，会显示很模糊。  看到你的仓库里写的是有更多配置， 但是没看太明白？ 博主可以更新下这个插件功能？

**Comment by LS1231** [comment]
已添加缩略图主要图区分功能
