### ISSUE TITLE
请问能否设置默认的宽度？

### ISSUE THREAD

**Issue by eaminhu** [LS1231/vue-preview#9]
现在遇到一个问题，一张高度比较高的图片。默认是以高度100%，我想以宽度100%，需要怎么设置？ 谢谢~

**Comment by lwdmengda** [comment]
同样遇到过，解决方法是创建一个Image对象，设置url，然后获取宽高（或许需要onload之后）。

**Comment by lwdmengda** [comment]
关于设置宽度和高度，下面代码供大家参考，前提是点击的图片和缩略图，是同一张图片。只需要在点击图片的时候设置宽高。
HTML
`    <section class="pics">
      <img class="preview-img" v-for="(item, index) in talkingPicList" :src="item.src" height="100" @click="setWidth($event,index);$preview.open(index, talkingPicList)">
    </section>`

JS
`  methods:{
    setWidth(evnet,index){
      this.talkingPicList.forEach(function(v,i){
        v.w=event.target.parentNode.childNodes[i].naturalWidth;
        v.h=event.target.parentNode.childNodes[i].naturalHeight
      })
    }
  },`

**Comment by eaminhu** [comment]
感谢~

**Comment by chengxianyi** [comment]
Cannot read property 'forEach' of undefined
用这个方法会报这个错

**Comment by chengxianyi** [comment]
我想让图片高度自适应
